# Generated by Django 6.0.6 on 2026-08-18

import billing.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("billing", "0001_initial")]

    operations = [
        migrations.CreateModel(name="RolePermission", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("role", models.CharField(max_length=30, unique=True)), ("dashboard", models.BooleanField(default=True)),
            ("products", models.BooleanField(default=False)), ("billing", models.BooleanField(default=False)),
            ("inventory", models.BooleanField(default=False)), ("discounts", models.BooleanField(default=False)),
            ("reports", models.BooleanField(default=False)), ("returns", models.BooleanField(default=False)),
            ("settings", models.BooleanField(default=False)),
        ], options={"ordering": ["role"]}),
        migrations.CreateModel(name="StoreSettings", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("store_name", models.CharField(default="Supermarket", max_length=150)),
            ("invoice_prefix", models.CharField(default="BILL-", max_length=12)),
            ("default_gst", models.DecimalField(decimal_places=2, default=Decimal("5.00"), max_digits=5)),
            ("max_cashier_discount", models.DecimalField(decimal_places=2, default=Decimal("10.00"), max_digits=5)),
            ("approval_threshold", models.DecimalField(decimal_places=2, default=Decimal("10.00"), max_digits=5)),
            ("round_off", models.DecimalField(decimal_places=2, default=Decimal("0.01"), max_digits=5)),
            ("whatsapp_enabled", models.BooleanField(default=False)),
        ], options={"verbose_name_plural": "store settings"}),
        migrations.CreateModel(name="AuditLog", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("action", models.CharField(max_length=120)), ("module", models.CharField(max_length=50)),
            ("object_type", models.CharField(blank=True, max_length=80)), ("object_id", models.CharField(blank=True, max_length=80)),
            ("ip_address", models.GenericIPAddressField(blank=True, null=True)), ("device", models.CharField(blank=True, max_length=255)),
            ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_logs", to=settings.AUTH_USER_MODEL)),
        ], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="PurchaseOrder", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("number", models.CharField(default=billing.models.purchase_order_number, max_length=40, unique=True)),
            ("order_date", models.DateField(default=django.utils.timezone.localdate)),
            ("status", models.CharField(choices=[("draft", "Draft"), ("pending", "Pending Approval"), ("approved", "Approved"), ("rejected", "Rejected"), ("received", "Received")], default="pending", max_length=12)),
            ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
            ("tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
            ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
            ("notes", models.TextField(blank=True)), ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_purchase_orders", to=settings.AUTH_USER_MODEL)),
            ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_purchase_orders", to=settings.AUTH_USER_MODEL)),
            ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_orders", to="billing.supplier")),
        ], options={"ordering": ["-order_date", "-created_at"]}),
        migrations.CreateModel(name="PurchaseOrderItem", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ("unit_cost", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
            ("tax_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
            ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
            ("tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
            ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_order_lines", to="billing.item")),
            ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="billing.purchaseorder")),
        ], options={"ordering": ["id"]}),
        migrations.CreateModel(name="ReturnRequest", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("number", models.CharField(default=billing.models.return_number, max_length=40, unique=True)), ("reason", models.TextField()),
            ("refund_method", models.CharField(choices=[("cash", "Cash"), ("original", "Original Payment"), ("credit", "Store Credit"), ("replacement", "Replacement")], max_length=15)),
            ("refund_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
            ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=10)),
            ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="returns", to="billing.invoice")),
            ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requested_returns", to=settings.AUTH_USER_MODEL)),
            ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_returns", to=settings.AUTH_USER_MODEL)),
        ], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="ReturnItem", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
            ("invoice_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="return_lines", to="billing.invoiceitem")),
            ("return_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="billing.returnrequest")),
        ]),
    ]
