# Generated by Django 6.0.6 on 2026-08-22 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_group_turmeric_under_groceries'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='auto_refill_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(db_index=True, default='Main Branch', max_length=120)),
                ('movement_type', models.CharField(choices=[('PURCHASE_TO_STORE', 'Purchase to store'), ('STORE_TO_SHELF', 'Store to shelf'), ('SHELF_TO_STORE', 'Shelf to store'), ('SALE_FROM_SHELF', 'Sale from shelf'), ('STOCK_ADJUSTMENT', 'Stock adjustment'), ('RETURN_TO_SUPPLIER', 'Return to supplier'), ('DISPOSAL', 'Disposal'), ('CLEARANCE_SALE', 'Clearance sale'), ('MANUAL_REFILL', 'Manual refill'), ('AUTO_REFILL', 'Auto refill'), ('INITIAL_STORE_STOCK', 'Initial store stock'), ('INITIAL_SHELF_STOCK', 'Initial shelf stock')], max_length=32)),
                ('source_location', models.CharField(blank=True, max_length=20)),
                ('destination_location', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('store_before', models.PositiveIntegerField()),
                ('store_after', models.PositiveIntegerField()),
                ('shelf_before', models.PositiveIntegerField()),
                ('shelf_after', models.PositiveIntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='billing.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShelfStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(db_index=True, default='Main Branch', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('target_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_quantity', models.PositiveIntegerField(default=0)),
                ('shelf_added_date', models.DateTimeField(blank=True, null=True)),
                ('last_refill_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_stocks', to='billing.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_stock_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'branch'), name='unique_shelf_stock_product_branch')],
            },
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(db_index=True, default='Main Branch', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('minimum_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stocks', to='billing.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_stock_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'branch'), name='unique_store_stock_product_branch')],
            },
        ),
    ]
