part of 'user_screens.dart';

class UserBillingScreen extends StatelessWidget { const UserBillingScreen(this.state, {super.key}); final UserState state;
  @override Widget build(BuildContext context) => UserShell(state: state, title: 'Billing / POS', child: Column(children: [
    Padding(padding: const EdgeInsets.all(12), child: TextField(onChanged: state.setSearch, decoration: const InputDecoration(hintText: 'Search or scan product', prefixIcon: Icon(Icons.search), suffixIcon: Icon(Icons.qr_code_scanner)))),
    SizedBox(height: 155, child: state.visibleProducts.isEmpty ? const EmptyMessage('No available products.') : ListView.builder(scrollDirection: Axis.horizontal, padding: const EdgeInsets.symmetric(horizontal: 8), itemCount: state.visibleProducts.length, itemBuilder: (_, i) { final p = state.visibleProducts[i]; return SizedBox(width: 150, child: UserCard(onTap: () => state.addProduct(p), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Icon(Icons.shopping_bag, color: userBlue), const Spacer(), Text('${p['name']}', maxLines: 2, overflow: TextOverflow.ellipsis, style: const TextStyle(fontWeight: FontWeight.w700)), Text(money(p['selling_price']), style: const TextStyle(color: userBlue, fontWeight: FontWeight.w800)), Text('${number(p['stock_quantity'])} available', style: const TextStyle(fontSize: 10))]))); })),
    const Divider(), Expanded(child: state.cart.isEmpty ? const EmptyMessage('Scan or tap a product to start a bill.') : ListView.builder(itemCount: state.cart.length, itemBuilder: (_, i) { final line = state.cart[i]; return ListTile(title: Text(line.name), subtitle: Text('${money(line.price)} × ${line.quantity} = ${money(line.total)}'), trailing: Row(mainAxisSize: MainAxisSize.min, children: [IconButton(onPressed: () => state.changeQuantity(line, -1), icon: const Icon(Icons.remove_circle_outline)), Text('${line.quantity}'), IconButton(onPressed: () => state.changeQuantity(line, 1), icon: const Icon(Icons.add_circle_outline))])); })),
    Container(color: Colors.white, padding: const EdgeInsets.all(14), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Subtotal'), Text(money(state.subtotal))]), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Estimated GST'), Text(money(state.gst))]), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Grand Total', style: TextStyle(fontWeight: FontWeight.w900, fontSize: 17)), Text(money(state.grandTotal), style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 17))]), const SizedBox(height: 8), ElevatedButton(onPressed: state.cart.isEmpty ? null : () => state.go(UserPage.payment, load: false), child: const Text('Proceed to Payment'))]))
  ]));
}
